name: "Bug Report"
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
labels: ["Priority"]
assignees: 
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        A brief description of the bug.

  - type: dropdown
    id: reporter
    attributes:
      label: Reporter
      description: The person reporting the bug.
      options:
        - Mariam Stepanyan
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug.
      placeholder: "Describe the bug"
    validations:
      required: false
  - type: input
    id: app_version
    attributes:
      label: Version
      description: The version of the application where the bug was found.
      placeholder: "Application version"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: The steps to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "Expected behavior"
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Actual behavior"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Add screenshots"
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: The environment where the bug occurred.
      options:
        - Prod
        - Test
    validations:
      required: false
  - type: checkboxes
    id: branches_dropdown
    attributes:
      label: Branches
      description: Choose from existing branches.
      options:
        - label: NAIRI-BK
        - label: EREBUNI-BK
        - label: SLAVMED-BK
    validations:
      required: false
  - type: input
    id: custom_branch
    attributes:
      label: Temporary Branch
      description: Enter a branch name if not listed above.
      placeholder: "Temporary branch"
    validations:
      required: false
