name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: 
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A brief description of the bug.
      placeholder: "Bug title"
    validations:
      required: true

  - type: input
    id: reporter
    attributes:
      label: Reporter
      description: The person reporting the bug.
      placeholder: "Your name"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug.
      placeholder: "Describe the bug"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version of Application
      description: The version of the application where the bug was found.
      placeholder: "Application version"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this bug.
      options:
        - P1
        - P2
        - P3
        - P4
        - P5
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: The steps to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "Expected behavior"
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Actual behavior"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Add screenshots"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: The environment where the bug occurred (e.g., browser, OS).
      placeholder: "Browser, OS"
    validations:
      required: false

  - type: dropdown
    id: branches_dropdown
    attributes:
      label: Select Branches
      description: Choose from existing branches.
      options:
        - NAIRI-BK
        - EREBUNI-BK
        - SLAVMED-BK
        - SLAVMED-BK-1953
    validations:
      required: false

  - type: input
    id: custom_branch
    attributes:
      label: Custom Branch
      description: Enter a branch name if not listed above.
      placeholder: "Custom branch"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Severity describes the impact of the defect on the application.
      options:
        - Critical
        - Blocking
        - Medium
        - Low
    validations:
      required: false
