name: "Test case"
description: File a Test Case.
title: "[TC: ] "
labels: ["Test Case", "triage"]
assignees: 
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        Title of the test case..
  - type: dropdown
    id: tester
    attributes:
      label: Tester
      description: Who is executing this test case?
      options:
        - Mariam Stepanyan
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this test case.
      options:
        - P1
        - P2
        - P3
        - P4
        - P5
    validations:
      required: false
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: What are the preconditions for this test case?
      placeholder: Describe any setup required before executing the test.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Test Steps
      description: What are the steps to execute this test case?
      placeholder: List the steps in detail.
    validations:
      required: false
  - type: textarea
    id: expected-results
    attributes:
      label: Expected Results
      description: What are the expected results of this test case?
      placeholder: Describe the expected outcome.
    validations:
      required: false
  - type: textarea
    id: actual-results
    attributes:
      label: Actual Results
      description: What are the actual results after executing the test case?
      placeholder: Describe the actual outcome.
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any additional comments or observations.
      placeholder: Add any relevant comments here.
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level for this test case.
      options:
        - Critical
        - Blocking
        - Medium
        - Low
    validations:
      required: false
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Select the status of this test case.
      options:
        - Passed
        - Failed
    validations:
      required: false
